<Project>
  <PropertyGroup>
	<RootNamespace>MultipleScreenPowersave</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
</Project>
