// <auto-generated/> - exclude file from stylecop checks
namespace MultipleScreenPowersave;

using Avalonia.Markup.Xaml;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public partial class AvaloniaApp : Avalonia.Application
{
    public override void Initialize()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
