// <auto-generated/> - exclude file from stylecop checks
#nullable enable

namespace MultipleScreenPowersave.Ui;

using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Platform;
using System.Diagnostics;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public partial class BlackWindow : Window
{
    private bool closeOnMouseMove;

    public BlackWindow() : this(closeOnMouseMove: false) { }

    public BlackWindow(bool closeOnMouseMove)
    {
        this.closeOnMouseMove = closeOnMouseMove;

        InitializeComponent();
    }

    private void Window_PointerMoved(object? sender, Avalonia.Input.PointerEventArgs e)
    {
        Close();
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
